/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardPlannerRouteImport } from './routes/dashboard.planner'
import { Route as DashboardNotesRouteImport } from './routes/dashboard.notes'
import { Route as DashboardCareerRouteImport } from './routes/dashboard.career'
import { Route as DashboardAiRouteImport } from './routes/dashboard.ai'
import { Route as DashboardNotesNoteIdRouteImport } from './routes/dashboard.notes.$noteId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/dashboard/profile',
  path: '/dashboard/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPlannerRoute = DashboardPlannerRouteImport.update({
  id: '/dashboard/planner',
  path: '/dashboard/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardNotesRoute = DashboardNotesRouteImport.update({
  id: '/dashboard/notes',
  path: '/dashboard/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCareerRoute = DashboardCareerRouteImport.update({
  id: '/dashboard/career',
  path: '/dashboard/career',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAiRoute = DashboardAiRouteImport.update({
  id: '/dashboard/ai',
  path: '/dashboard/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardNotesNoteIdRoute = DashboardNotesNoteIdRouteImport.update({
  id: '/$noteId',
  path: '/$noteId',
  getParentRoute: () => DashboardNotesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/career': typeof DashboardCareerRoute
  '/dashboard/notes': typeof DashboardNotesRouteWithChildren
  '/dashboard/planner': typeof DashboardPlannerRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/notes/$noteId': typeof DashboardNotesNoteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/career': typeof DashboardCareerRoute
  '/dashboard/notes': typeof DashboardNotesRouteWithChildren
  '/dashboard/planner': typeof DashboardPlannerRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/notes/$noteId': typeof DashboardNotesNoteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/career': typeof DashboardCareerRoute
  '/dashboard/notes': typeof DashboardNotesRouteWithChildren
  '/dashboard/planner': typeof DashboardPlannerRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/notes/$noteId': typeof DashboardNotesNoteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard/ai'
    | '/dashboard/career'
    | '/dashboard/notes'
    | '/dashboard/planner'
    | '/dashboard/profile'
    | '/dashboard/'
    | '/dashboard/notes/$noteId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard/ai'
    | '/dashboard/career'
    | '/dashboard/notes'
    | '/dashboard/planner'
    | '/dashboard/profile'
    | '/dashboard'
    | '/dashboard/notes/$noteId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard/ai'
    | '/dashboard/career'
    | '/dashboard/notes'
    | '/dashboard/planner'
    | '/dashboard/profile'
    | '/dashboard/'
    | '/dashboard/notes/$noteId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  DashboardAiRoute: typeof DashboardAiRoute
  DashboardCareerRoute: typeof DashboardCareerRoute
  DashboardNotesRoute: typeof DashboardNotesRouteWithChildren
  DashboardPlannerRoute: typeof DashboardPlannerRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/planner': {
      id: '/dashboard/planner'
      path: '/dashboard/planner'
      fullPath: '/dashboard/planner'
      preLoaderRoute: typeof DashboardPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/notes': {
      id: '/dashboard/notes'
      path: '/dashboard/notes'
      fullPath: '/dashboard/notes'
      preLoaderRoute: typeof DashboardNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/career': {
      id: '/dashboard/career'
      path: '/dashboard/career'
      fullPath: '/dashboard/career'
      preLoaderRoute: typeof DashboardCareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/ai': {
      id: '/dashboard/ai'
      path: '/dashboard/ai'
      fullPath: '/dashboard/ai'
      preLoaderRoute: typeof DashboardAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/notes/$noteId': {
      id: '/dashboard/notes/$noteId'
      path: '/$noteId'
      fullPath: '/dashboard/notes/$noteId'
      preLoaderRoute: typeof DashboardNotesNoteIdRouteImport
      parentRoute: typeof DashboardNotesRoute
    }
  }
}

interface DashboardNotesRouteChildren {
  DashboardNotesNoteIdRoute: typeof DashboardNotesNoteIdRoute
}

const DashboardNotesRouteChildren: DashboardNotesRouteChildren = {
  DashboardNotesNoteIdRoute: DashboardNotesNoteIdRoute,
}

const DashboardNotesRouteWithChildren = DashboardNotesRoute._addFileChildren(
  DashboardNotesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  DashboardAiRoute: DashboardAiRoute,
  DashboardCareerRoute: DashboardCareerRoute,
  DashboardNotesRoute: DashboardNotesRouteWithChildren,
  DashboardPlannerRoute: DashboardPlannerRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
